### ISSUE TITLE
Support android

### ISSUE THREAD

**Issue by edisontrent1337** [kiliankoe/MensaDresden#29]
It would be nice to have a version that runs on android.
Maybe it makes sense to migrate to react-native or flutter?

**Comment by kiliankoe** [comment]
This app came to be since the StuWe released their official API ***and*** I wanted to play around with SwiftUI. Without the latter I wouldn't have built this app. 
There's already quite a few cross-platform alternatives (some obviously built using flutter, no clue about other stacks) in the App/Play Stores.

I'm not going to be the one building a cross-platform equivalent here, but be my guest 👍 Or you know, start using iOS 😅
